### ISSUE TITLE
Plugins manifest

### ISSUE THREAD

**Issue by Ahmed-90** [Lamassau/PiTrol#16]
Plugins Manifest should be in a `.json` file in the plugin root folder and should contain:
(obviously some are optional)

- Plugin Name. 
- Plugin Description.
- Plugin Version.
- Plugin Icon.
- Valid PiTrol Versions.
- Valid Pi Models.
- Valid Node Versions.
- Author Name.
- Git Repo.
- License.
- Dependencies.

**Comment by AlKass** [comment]
Please add this as a task to the waffle management board. We'll plan for the implementation of this feature as a team

**Comment by Ahmed-90** [comment]
hehe i have no idea how o.O my dashboard seems minimal and/or no permissions (first time using waffle.io :D)

**Comment by AlKass** [comment]
What does it say when you click this link?

https://waffle.io/AlKass/PiTrol

**Comment by Ahmed-90** [comment]
i can see the issues but cant move or do anything other that commenting/creating issues

**Comment by AlKass** [comment]
An issue is a task. Create an issue and mark it as an enhancement

**Comment by Ahmed-90** [comment]
i just did it created https://github.com/fadeenk/PiTrol/issues/20 
no options to mark it as enhancement or anything o.O

**Comment by fadeenk** [comment]
I would add the following to support at least #4
triggers: [NONE, CRON, HTTP, SYSEVENT, GPIO]
triggerMethod: // different for each method cron takes cron format, HTTP takes the HTTP method it support and so on...
for #5 we might want to add another type of trigger PLUGIN? meaning another plugin will trigger it however it makes things a bit more complicated  but it should work here is an example for the triggers section

```JSON
{
  "triggers": ["HTTP", "PLUGIN"],
  "triggerMethod": {
    "HTTP": ["GET", "POST"],
    "PLUGIN": {
      //TBD
    }
  }
}
```

**Comment by fadeenk** [comment]
@AlhasanIQ what do you think about the above?

**Comment by AlKass** [comment]
@Ahmed-90 
Could you please put together a manifest file and place it under `plugins/PiStatus`?

**Comment by Ahmed-90** [comment]
@AlKass I'm finalizing a project atm will do that as soon as i can

**Comment by AlhasanIQ** [comment]
any takes on the current manifest ? 
is this issue closed now ?
