### ISSUE TITLE
Unify plugin request handlers and UI/React object in one plugin

### ISSUE THREAD

**Issue by AlKass** [Lamassau/PiTrol#22]
I will take this up as a priority and finish it today

**Comment by AlKass** [comment]
@fadeenk 
@AlhasanIQ 
This feature will require us to move to ES6 syntax

**Comment by fadeenk** [comment]
Which part of es6 do we need for it? Node6 supports most of es6 features...

**Comment by Ahmed-90** [comment]
the only obviously needed ES6 feature that is not in node6 is "import" and can easily be avoided with require for now

**Comment by AlKass** [comment]
we need to at least be able to use the 'import' keyword

**Comment by AlKass** [comment]
@Ahmed-90 
Well the thing is, we don't want to force React developers to conform to our standards. We'd like to allow people to use existing 3rd party components without the need to modify a single line of code in there

**Comment by Ahmed-90** [comment]
import needs runtime flag to work out of the box without babel

**Comment by Ahmed-90** [comment]
@AlKass am with you on this one... react needs its full power

**Comment by fadeenk** [comment]
If we only need import we could use the harmony flag for now

**Comment by AlKass** [comment]
@fadeenk 
Yeah, there are get-arounds we can employ for now, but like I said, we don't want anyone to be forced to conform to our standards. If we (or even future customers) decide to use some off-the-shelf 3rd party components that happen to use the 'import' keyword, now everyone is forced to modify the component in order to get it to work with PiTrol. Not sure if people'd find that convenient

**Comment by fadeenk** [comment]
We can add babel with [node6 preset](https://github.com/salakar/babel-preset-node6) along with [react preset](https://github.com/babel/babel/tree/master/packages/babel-preset-react) which should cover all of react use cases
