### ISSUE TITLE
Using github projects to manage this repo rather than waffle.io

### ISSUE THREAD

**Issue by fadeenk** [Lamassau/PiTrol#26]
I like github projects much more than waffle.io

Is there a reason to why we are using it over github projects?

@AlKass @AlhasanIQ @Ahmed-90

**Comment by AlKass** [comment]
I like the visual representation of Waffle.io better. No technical reasons really

**Comment by fadeenk** [comment]
I vote for github's projects because
- fully integrated 
- easier to manage issues
- easier to manage releases
- easier access for everyone (new people can just look at the projects and see what is going on without leaving the repo)

**Comment by AlhasanIQ** [comment]
it looks cool,
lets give it a couple of days as a test
