### ISSUE TITLE
React won't build any components that reside outside the src/ directory

### ISSUE THREAD

**Issue by AlKass** [Lamassau/PiTrol#30]
This is preventing us from containing the plugin and the actual UI component. After several hours of trying to all different types of possible get-arounds, I suggest you keep the two items separate

**Comment by Ahmed-90** [comment]
not pro react dev 😜 but what about react SSR?

**Comment by fadeenk** [comment]
What about setting up a prebuild script that iterates over the plugins extract the react components and moves them into the src folder?  I am horrible with react just throwing ideas here :P

**Comment by AlhasanIQ** [comment]
@fadeenk 's idea is perfect
found a similar scenario in the `create-react-app`'s docs

```diff
   "scripts": {
+    "move-plugins": "react-scripts build",
-    "build": "react-scripts build",
+    "build": " npm run move-plugins && react-scripts build",
   }
```
all we have to do is to make a script (`move-plugins`) to move the plugins before building

**Comment by AlKass** [comment]
@AlhasanIQ 
trying this tomorrow

**Comment by AlhasanIQ** [comment]
if this doesnt work we will have to `npm run eject`
but this has to be the last resort

**Comment by fadeenk** [comment]
I would try somthing similar to this (just a small spin of @AlhasanIQ  code)

```diff
   "scripts": {
+    "move-plugins": "node move-plugins",
+    "prebuild": "npm run move-plugins",
     "build": "react-scripts build",
   }
```

I would like to keep the script syntax clean and following [npm's spec for scripts](https://docs.npmjs.com/misc/scripts)

**Comment by AlKass** [comment]
Can someone write this module?
I'm running a little short on time, and I may not get the chance to put it together today.

Make it a package that runs as follows:

`node move-plugins --source plugins/ --dest src/`

**Comment by AlKass** [comment]
or we could stick to a dirty little `bash` command for now, e.g. `cp -r plugins/ src/`

**Comment by AlKass** [comment]
never mind. I got it

**Comment by AlhasanIQ** [comment]
@AlKass can you please reference commits on comments in the future?

**Comment by AlKass** [comment]
@AlhasanIQ 
sure
