### ISSUE TITLE
Proposing the isCompatible plugin function

### ISSUE THREAD

**Issue by AlKass** [Lamassau/PiTrol#33]
Instead of us having to worry about which plugins are compatible with which version of pi the user happens to be using, why don't we allow the user to perform all the check they need to do and allow us a reference to an isCompatible function that tells us whether the plugin is compatible along with any warning/error messages we need to print to the user at the website?

**Comment by fadeenk** [comment]
I agree and we should have access to that information if we are using the proposed plugin manifest #16

**Comment by Ahmed-90** [comment]
yep that's the point of the manifest to have these info available without the need to invoke the plugin code etc..
just let that function check the manifest and ggwp
