### ISSUE TITLE
Automated Testing Modification Request

### ISSUE THREAD

**Issue by AlKass** [Lamassau/PiTrol#39]
The automated tests need to recognize the following as errors

```
/home/travis/build/fadeenk/PiTrol/plugins/PiStatus/uicomponent.js

   1:8  error  'React' is defined but never used  no-unused-vars

  15:5  error  'fetch' is not defined             no-undef
```

**Comment by AlKass** [comment]
@fadeenk 
just making sure you didn't overlook this

**Comment by fadeenk** [comment]
sorry was at work just got home will look at it now

**Comment by fadeenk** [comment]
Ok I updated it,

React is not used so to fix that one you just need to not import it
for the fetch i made it into a global variable so it wont display the error anymore

**Comment by AlKass** [comment]
React needs to be imported regardless of whether it is used or not. Try commenting it out and the build engine will yell at you from everywhere

**Comment by fadeenk** [comment]
got it i am fix it, sorry about that. Not so good with react so i dont know the exact details

**Comment by fadeenk** [comment]
@AlKass is there anything else needed for this?? if not we can close the issue
