### ISSUE TITLE
Plugin Design Conventions

### ISSUE THREAD

**Issue by AlKass** [Lamassau/PiTrol#40]
Let's agree on some design standards before we start writing our plugins

if we use a command that returns something in the following format:

`key1=value1`
`key2=value2`
`key3=value3`
`key4=value4`

we return (using `res.status(200).json({/*data here*/})`) the data as follows:

```javascript
{
    key1: value1,
    key2: value2,
    key3: value3,
    key4: value4
}
```

if we use a command that returns something in the following format:

`key(id): value`

we return the data as follows:

```javascript
{
    key_id: value
}
```

if we use a command that returns something in the following format:

`object: key=value`

we return the data as follows:

```javascript
{
    object: {
        key: value
   }
}
```

Let's maintain this issue for convention-related discussions only

**Comment by fadeenk** [comment]
I would propose something more like this, the defintions are [jsDoc standard](http://usejsdoc.org/index.html) and i provide a simple example
```javascript
/**
* @typedef {Object} response 
* @param {Boolean} response.success - if the return data is a successful response or an error
* @param {*} response.data - can be in any format that the plugin needs it in if successful, if failed should follow the error structure
**/ 
response = {
  success: true,
  data: {whatever: 'it needs to be'}
}

/**
@typedef {Object} error
@param {Number} error.code - the error code (used for localization)
@param {String} error.message - the message to display for user
@param {String} error.plugin - plugin's name
@param {Stack} error.stack - the call stack that triggered the error
@param {*} [error.payload] - the extra data to send for the plugin if needed
**/
error = {
  code: 0,
  message: 'plugin exploded',
  plugin: 'my bad plugin',
  payload: {
     info: 'my extra info to help me fix this or display better errors to the user like which part caused the issue'
  },
  stack: // the error stack (too lazy to find one)
}
```
