### ISSUE TITLE
Swags : in-browser SSH session and OS Level package management 

### ISSUE THREAD

**Issue by mustafa96m** [Lamassau/PiTrol#42]
Hi, guys!

I feel like adding in-browser ssh would be great because it's a hassle for windows people and imagine like you can control it from your Mobile phone right away from your browser and to spice things up you may add external connectivity module support to handle gsm or wifi modules so now the device is fully controllable from everywhere.

Same thing goes for package management as well

**Comment by AlKass** [comment]
it would be great if you could find us a lightweight in-browser SSH client we could integrate

**Comment by Ahmed-90** [comment]
Remote SSH can be done with little twist .. our own command/output forwarding plugin? 
wifi is built in so yolo :P
gsm support from my experience .. its a pain.. there is a lot of modules each with its own setup and set of issues  
maybe we can add automated setup for 3G usb dongles with `sakis3g` it has been the best for me so far

**Comment by AlKass** [comment]
@mustafa96m 
any update on this?

**Comment by AlhasanIQ** [comment]
if @mustafa96m still wants to do it i'd suggest closing this issue and opening an issue for each plugin ( one for ssh , one for package management )

**Comment by fadeenk** [comment]
Think we should have an issue that has a list of all the plugins that references the individual plugin issues. This way we can close the issues that have individual suggestions and have the master issue that tracks the plugins progress and status

**Comment by mustafa96m** [comment]
@AlKass @AlhasanIQ sorry for being late, and that would be great actually and if I have the time I will push PR there.
