### ISSUE TITLE
Datastore Related

### ISSUE THREAD

**Issue by AlKass** [Lamassau/PiTrol#44]
What exactly is the point of a plugin datastore in this project? I think I'm a little fuzzy on the concept

**Comment by Ahmed-90** [comment]
historical data? for example sysinfo cpu/ram/network/temp charts from x to y ?

**Comment by AlKass** [comment]
@Ahmed-90 
so we're not using it to store any plugin metadata is what i'm trying to make sure of

**Comment by Ahmed-90** [comment]
nope thats why we should have filebased manifest and configs

**Comment by AlhasanIQ** [comment]
why not to store preferences ? :(

**Comment by fadeenk** [comment]
configs can be in the datastore, or filebased depending on the plugin. The manifest will be file based for sure.

**Comment by Ahmed-90** [comment]
sure configs can be in db 
but.. personally i think the best configs setup should be accessible "on the fly" from outside of the system and should be cached on startup and update on user request
>  just personal preferance

**Comment by fadeenk** [comment]
@Ahmed-90 i agree but some plugins might want/need to store some configs in a data store so makes more sense to allow for configs to be boths
