### ISSUE TITLE
Unrealistic Setup Time

### ISSUE THREAD

**Issue by AlKass** [Lamassau/PiTrol#54]
I just checkout the code on a Raspberry Pi B Module (512MB of memory), and `npm install` has been running for the last 4 hours and still going. This needs to be tuned up to a more realistic time figure.

Any suggestions on how we could go about doing that?

**Comment by mustafa96m** [comment]
Will forking these modules into the project reduce the setup time?

**Comment by fadeenk** [comment]
@mustafa96m not really you would still need to copy all that data into the pi
@AlKass the best approach I could think of is bundling and generating minified builds.

For example once the front end is built we dont really need to get all the dependencies needed for react which are the majority. So in theory, we could build everything on a beefy machine (dev machine), then use the generated build for the pi which will only have the components needed to run it, none of the dev deps and it will already be transpiled to run on node without babel and so on

**Comment by Ahmed-90** [comment]
i think we are doing the react part wrong...  
we should not compile/babel/minify on the Pi.. we should provide clean `dist` files

**Comment by fadeenk** [comment]
I agree with @Ahmed-90 's comment, I just was still asleep when I replied 😄

**Comment by AlhasanIQ** [comment]
two points
@AlKass which part took the most time ? npm install ? npm run build ? 
@Ahmed-90 what if a user makes his own plugin ? does he get to rebuild or does he have to get a separate development package

**Comment by Ahmed-90** [comment]
@AlhasanIQ we should provide a clean API so when a user want to build his own he just connect to the interface i don't think its logical to have a full building process in the final product

**Comment by AlKass** [comment]
@AlhasanIQ , I fell asleep waiting on `npm install` to finish. Haven't had the chance to run `npm run build` yet.
@Ahmed-90, we will continue to maintain the React part of the project in the project directory, so the user can always choose to build from scratch if he/she is willing to wait. That said, we still need to find ways to minimize the time required for the build process to run.

**Comment by Ahmed-90** [comment]
@AlKass well.. logically you shouldn't ship source with the controller.. not everyone is a developer and not everyone want to build plugins..

source should be provided in a different package... maybe an option during instillation or something

**Comment by AlKass** [comment]
@Ahmed-90 
In that case, we could maintain the source in a different repository and link it to PiTrol as a submodule. That way developers can add `--recursive` to `git clone` and get the source as part of the developer tool set.
