### ISSUE TITLE
PiTrol Plugin Manager

### ISSUE THREAD

**Issue by Alkass** [Lamassau/PiTrol#58]
I'm building a standalone plugin manager with the following characteristics

* Ability to create a plugin template
  > This will simply be a function that checks out [this](https://github.com/Lamassau/pitrol-generic-template) template and places it under the `plugins/` directory.

* Ability to download and install 3rd party plugins.
  > Developers will be able to write their own plugins and check them in as repositories on GitHub. This function will check out these plugins, places them under `plugins/` and installs all the required node modules.

Any suggestions or requests before I start?

**Comment by Ahmed-90** [comment]
good, we need a whole new approach for this tool.. a onetime package/build system is a must 
this manager can be more like a PiTrol builder ?

**Comment by AlKass** [comment]
if by a 'PiTrol builder' you're referring to a tool that can build the whole project from scratch through an automated process, sure

**Comment by AlKass** [comment]
@fadeenk 
@AlhasanIQ 
your take on this before I proceed?

**Comment by fadeenk** [comment]
I like the idea but will wait till the weekend to make sure we map everything out and understand how everything will work before we jump in head first and things get confusing. 

I will propose a plan over the weekend that will go over the plan and potential future of this project

**Comment by fadeenk** [comment]
Hey guys I am sorry but I am sick and feeling horrible cant even thing anymore

**Comment by fadeenk** [comment]
I have been doing some research and react dev environment is just too big for the pi...

**Comment by AlKass** [comment]
what are our options?

**Comment by Ahmed-90** [comment]
provide pre built pages

**Comment by fadeenk** [comment]
Doing the frontend on the pi wont be possible like @Ahmed-90 said we probably wanna have a prebuilt pages with debug plugins. The debug plugins will dump all data so you can see what the pi returns. Then build the frontend on a more powerful machine.

**Comment by Ahmed-90** [comment]
are you guys open for a hardcore approach ? 💡 

> *dropping react* ?

**Comment by fadeenk** [comment]
I think react is the way to go maybe just having a different dev environment on the pi makes more sense. Its just react will allow us to take advantage of components and easy module/components management if we want to scale this

**Comment by Ahmed-90** [comment]
My question was to just check the waters tbh 😜 

here is my idea... we use react to build a skeleton that serves the core pages..
and use an extended markdown parser to parse files for the plugins pages? 
so the benefits will be:
- Plugins pages Parsing will be clientside.
- No need to recompile every time a plugin changes, add, deleted.
- Build only once and provide a prebuilt `js, css, html`.
- Get rid of any complications a 3rd party user may create with there own plugins/tools.
- Give the ability to build plugins for those who don't know/like react.
- Keep the design unified even with 3rd party plugins.

**Comment by AlKass** [comment]
can we consider other React alternatives? [`Rax`](http://rax.taobaofed.org/), [`inferno`](https://infernojs.org/), and [`Preact`](https://preactjs.com/) are two I'm aware of

**Comment by Ahmed-90** [comment]
@AlKass wont make much difference all need to be compiled 
these frameworks are there mostly to make it lighter in the browser not on build times

**Comment by AlKass** [comment]
@Ahmed-90 
the alternatives are designed to be lightweight, so they **might** take less time to compile

**Comment by Ahmed-90** [comment]
@AlKass still.. removing the compile process from the Pi is a huge gain. not just time think of js building issues.. future node updates etc...

also think of the hobbyists and the huge non developers users of the PI

**Comment by AlKass** [comment]
@Ahmed-90 
I am really trying to find ways to make the developer's experience as smooth as possible. Yes, not everyone is a developer, but I bet developers won't be happy as they have to wait for 4+ hours for `npm install && npm run build` to finish as they write their plugins.

**Comment by Ahmed-90** [comment]
yep.. lets just provide prebuilt panel with "compile yourself" and `src` options

**Comment by fadeenk** [comment]
I think the best approach is to have a basic dev frontend where you can display the pi data and see what is returned then take that and build the react components on a stronger machine
